# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: azure-automotive-ai
metadata:
  template: azure-automotive-ai

hooks:
    postprovision:
      posix:
        shell: sh
        run: azd env get-values > .env;
        interactive: true
        continueOnError: false
      windows:
        shell: pwsh
        run: $output = azd env get-values; Add-Content -Path .env -Value $output;
        interactive: true
        continueOnError: false
pipeline:
  variables:
      - AZURE_OPENAI_RESOURCE
      - AZURE_OPENAI_RESOURCE_GROUP
      - AZURE_OPENAI_RESOURCE_GROUP_LOCATION
      - AZURE_OPENAI_SKU_NAME
      - AZURE_OPENAI_API_VERSION
      - CREATE_ROLE_FOR_USER