"""
This module defines a dictionary for voice commands.
"""
# voice commands dictionary
voice_commands = {
    "start a diagnostic report": "DIAGNOSTIC_REPORT",
    "send a diagnostic report to my email": "send_diagnostic_report",
    "engine rpm": "010C",
    "intake air temperature": "010F",
    "fuel tank level": "012F",
    "time run with MIL on": "014D",
    "engine coolant temperature": "0105",
    "read trouble codes": "03",
    "freeze frame data": "0202",
    "pending trouble codes": "07",
    "clear trouble codes": "04",
    "service 9 supported pids": "0900",
    "vin message count": "0901",
    "vehicle identification number": "0902",
    "calibration id message count": "0903",
    "calibration id": "0904",
    "cvn message count": "0905",
    "calibration verification numbers": "0906",
    "in-use performance tracking message count": "0907",
    "in-use performance tracking spark ignition": "0908",
    "ecu name message count": "0909",
    "ecu name": "090A",
    "in-use performance tracking compression ignition": "090B",
    "what's next on my calendar": "next_appointment",
    "create a new appointment": "create_appointment",
    "do I have any new emails": "check_outlook_email",
    "send an email with an attachment": "send_email",
    "I have a question": "ASK_CHATGPT_QUESTION",
    "start data stream": "START_DATA_STREAM",
    "stop data stream": "STOP_DATA_STREAM",
    "save data to spreadsheet": "SAVE_DATA_TO_SPREADSHEET",
    "let's have a conversation": "START_CONVERSATION",
}

# ELM327 commands set
ELM327_COMMANDS = {
    "DIAGNOSTIC_REPORT",
    "010C",
    "010F",
    "012F",
    "014D",
    "0105",
    "03",
    "0202",
    "07",
    "04",
    "0900",
    "0901",
    "0902",
    "0903",
    "0904",
    "0905",
    "0906",
    "0907",
    "0908",
    "0909",
    "090A",
    "090B",
}
