name: markdown-lint

on:
  push:
    branches: [ "azure_openai" ]
    paths:
      - '**/*.md'
  pull_request:
    branches: [ "azure_openai" ]
    paths:
      - '**/*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: ${{ github.event_name != 'push' && github.event.pull_request.draft == false }}
    runs-on: ["ubuntu-22.04", "ubuntu-24.04"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v1
        with:
          node-version: '20'
      - name: Install Markdownlint CLI
        run: npm install -g markdownlint-cli
      - name: Run Markdownlint
        run: markdownlint -c markdownlint-config.json "**/*.md"
